INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1401',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1402',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1403',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1404',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1405',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1406',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1407',24);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1408',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1409',18);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1410',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1411',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1413',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1416',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1417',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1419',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1420',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1424',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1425',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1426',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1428',25);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1429',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministro', '1430',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1431',16);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1432',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministro', '1433',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1434',32);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1436',24);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1438',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1439',14);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1440',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1441',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1442',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1444',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1445',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1448',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1449',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1450',8);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1451',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1454',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1455',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1456',12);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1457',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1458',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1460',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1461',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1462',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1463',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1464',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1465',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1466',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1468',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1469',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1472',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1473',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1474',12);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1475',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1476',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1477',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1479',24);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1481',16);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1482',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministro', '1483',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1484',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1485',19);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1486',33);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1488',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1489',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1490',26);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1491',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministro', '1492',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1493',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1494',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1495',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1496',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1497',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1498',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1500',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1501',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1502',17);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1503',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1506',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1508',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Operaciones', '1509',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1510',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1512',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1513',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1515',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1517',12);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1518',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1520',27);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1521',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1522',13);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1523',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1524',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Operaciones', '1526',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1528',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1530',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1531',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1532',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1533',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1536',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1537',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1538',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1539',11);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1540',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1541',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1542',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1543',26);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1544',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1545',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1548',9);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1550',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1551',35);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1553',25);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministros', '1554',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1555',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1556',13);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1558',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministros', '1559',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1560',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1561',19);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1564',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1565',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1566',23);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1568',11);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1569',11);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1570',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1571',14);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1572',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1587',12);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1588',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1589',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1590',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1592',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1593',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1594',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1596',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1597',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1599',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1600',22);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1601',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1602',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1603',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1604',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1605',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1606',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1607',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1608',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1610',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministro', '1612',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1613',9);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1616',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministro', '1617',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1618',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministro', '1620',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '1621',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Operaciones', '1622',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '1623',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '1624',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '1625',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '1626',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Logística Internacional', '1627',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '1628',2);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1689',25);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1774',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1775',25);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1794',24);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1795',23);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1796',11);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1798',23);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1799',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1800',24);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '1802',20);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', '9507',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '9530',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '9531',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '9532',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '9533',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Robótica y Manufactura', '9535',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ingeniería', '9536',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Ciencia de Datos', '9539',21);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Doctorado en Inteligencia Artificial', '9899',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Dirección de Operaciones', '9939',1);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', '9940',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Simuladores Gráficos', '10235',4);
