INSERT INTO Clase_programa (no_clase, programa) VALUES ('8784', 'Maestría en Dirección de Instituciones Educativas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1046', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11559', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1047', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11557', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10925', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('12136', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10924', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11554', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10921', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11556', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1045', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10923', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11563', 'Maestría en Comunicaciones de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11548', 'Especialidad en Relaciones Públicas y Reputación de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11550', 'Especialidad en Relaciones Públicas y Reputación de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11549', 'Especialidad en Relaciones Públicas y Reputación de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11545', 'Especialidad en Relaciones Públicas y Reputación de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11547', 'Especialidad en Relaciones Públicas y Reputación de Marca');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10912', 'Especialidad en Publicidad y Creación de Contenidos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1038', 'Especialidad en Publicidad y Creación de Contenidos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1037', 'Especialidad en Publicidad y Creación de Contenidos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1036', 'Especialidad en Publicidad y Creación de Contenidos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1375', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1360', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1376', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('12071', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1365', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1369', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1371', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1377', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1361', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1368', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1387', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('12072', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1362', 'Maestría en Dirección del Capital Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1098', 'Maestría en Narrativa y Producción Audiovisual');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1097', 'Maestría en Narrativa y Producción Audiovisual');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1159', 'Maestría en Narrativa y Producción Audiovisual');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1160', 'Maestría en Narrativa y Producción Audiovisual');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1158', 'Maestría en Narrativa y Producción Audiovisual');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1157', 'Maestría en Narrativa y Producción Audiovisual');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1105', 'Maestría en Comunicación Política y Pública');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1104', 'Maestría en Comunicación Política y Pública');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1103', 'Maestría en Comunicación Política y Pública');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1175', 'Maestría en Comunicación Política y Pública');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1173', 'Maestría en Comunicación Política y Pública');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1172', 'Maestría en Comunicación Política y Pública');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1171', 'Maestría en Comunicación Política y Pública');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('9934', 'Maestría en Comunicación Institucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1118', 'Maestría en Comunicación Institucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1116', 'Maestría en Comunicación Institucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1120', 'Maestría en Comunicación Institucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1165', 'Maestría en Comunicación Institucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1119', 'Maestría en Comunicación Institucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1163', 'Maestría en Comunicación Institucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1164', 'Maestría en Comunicación Institucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1105', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1107', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1098', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1104', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1102', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1099', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1088', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1086', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1097', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1100', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1081', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1096', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1093', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1225', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1226', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1227', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1228', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1216', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1215', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1214', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1213', 'Maestría en Mercadotecnia Estratégica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1163', 'Maestría en Negocios Internacionales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1164', 'Maestría en Negocios Internacionales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1161', 'Maestría en Negocios Internacionales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1108', 'Maestría en Negocios Internacionales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1106', 'Maestría en Negocios Internacionales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1103', 'Maestría en Negocios Internacionales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1165', 'Maestría en Negocios Internacionales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1109', 'Maestría en Negocios Internacionales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1101', 'Maestría en Negocios Internacionales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1156', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1154', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1160', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1147', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1151', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1152', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1133', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1132', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1149', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1150', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1130', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1131', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1146', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1148', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1222', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1128', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1223', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1224', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1212', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1211', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1129', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1210', 'Maestría en Impuestos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1127', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1126', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1117', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1116', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1125', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1124', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1114', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1115', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1123', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1122', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1112', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1113', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1121', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1120', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1118', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1221', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1173', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1175', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1171', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1170', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1209', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1119', 'Maestría en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1166', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1167', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1168', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1094', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1290', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1095', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1289', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1085', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1090', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1082', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1092', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1083', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1084', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1089', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1087', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1229', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1230', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1231', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1232', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1220', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1219', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1218', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1217', 'Maestría en Administración de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1291', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1288', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1293', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1176', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1177', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1178', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1518', 'Maestría en Derecho Laboral');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1334', 'Maestría en Derecho Laboral');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1332', 'Maestría en Derecho Laboral');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1330', 'Maestría en Derecho Laboral');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1284', 'Maestría en Derecho Laboral');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1278', 'Maestría en Derecho Laboral');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11933', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11946', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11930', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11931', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11940', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11928', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11953', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11954', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11951', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11952', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11956', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11955', 'Maestría en Gestión de las Artes y Políticas Culturales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10733', 'Maestría en Gobierno y Políticas Públicas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10654', 'Maestría en Gobierno y Políticas Públicas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10653', 'Maestría en Gobierno y Políticas Públicas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('2688', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1007', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1015', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1008', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1002', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1016', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('2816', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('2817', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1010', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('2815', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1006', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1012', 'Maestría Internacional en Finanzas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1357', 'Doctorado en Bioética');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1358', 'Doctorado en Bioética');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1359', 'Doctorado en Bioética');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1598', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1506', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1536', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1417', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1476', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1493', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1591', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1858', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1516', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1611', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1424', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1774', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1799', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1802', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1859', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1796', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1798', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1801', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1855', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1856', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1803', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1797', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1857', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1800', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1795', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1775', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1689', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1794', 'Maestría en Ciencia de Datos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1455', 'Especialidad en Gestión de Eventos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('6653', 'Especialidad en Gestión de Eventos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('6652', 'Especialidad en Gestión de Eventos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1388', 'Especialidad en Gestión de Eventos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('6651', 'Especialidad en Gestión de Eventos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1448', 'Especialidad en Gestión de Eventos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1386', 'Especialidad en Gestión de Eventos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1384', 'Especialidad en Gestión de Eventos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1235', 'Especialidad en Emprendedores de Negocios de Alimentos y Bebidas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1378', 'Especialidad en Emprendedores de Negocios de Alimentos y Bebidas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1374', 'Especialidad en Emprendedores de Negocios de Alimentos y Bebidas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1599', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1455', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1625', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1495', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1593', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1511', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1606', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1419', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1402', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1461', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1531', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1443', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1467', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1449', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1501', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1538', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1412', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1473', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1587', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1566', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1436', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1479', 'Especialidad en Ingeniería y Gestión Ambiental');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10439', 'Maestría en Dirección de Instituciones de Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10438', 'Maestría en Dirección de Instituciones de Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10433', 'Maestría en Dirección de Instituciones de Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10950', 'Maestría en Dirección de Instituciones de Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10949', 'Maestría en Dirección de Instituciones de Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10418', 'Maestría en Dirección de Instituciones de Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10947', 'Maestría en Dirección de Instituciones de Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10948', 'Maestría en Dirección de Instituciones de Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11609', 'Maestría en Anticorrupción');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11599', 'Maestría en Anticorrupción');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11614', 'Maestría en Anticorrupción');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11608', 'Maestría en Anticorrupción');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1582', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1136', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1583', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1585', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1586', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1137', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1140', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1139', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1157', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1141', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1158', 'Doctorado en Ciencias Empresariales');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1559', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1483', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1433', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1549', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1554', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1427', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1492', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1430', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1519', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1527', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1620', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1525', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1612', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1507', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1617', 'Maestría en Ingeniería y Gestión de la Cadena de Suministro');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1588', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1565', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1489', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1441', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1437', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1567', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1480', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1484', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1560', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1438', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1564', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1488', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1440', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1408', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1410', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1487', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1544', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1546', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1552', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1435', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1521', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1523', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1558', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1482', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1432', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1550', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1555', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1426', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1491', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1429', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1518', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1528', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1621', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1524', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1613', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1508', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1618', 'Maestría en Ingeniería');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1590', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1485', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1561', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1439', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1589', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1572', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1556', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1481', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1431', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1569', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1616', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1571', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1407', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1409', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1486', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1543', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1545', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1551', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1434', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1520', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1522', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1604', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1600', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1601', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1602', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1603', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1454', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1456', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1457', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1458', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1459', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1624', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1626', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1627', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1623', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1628', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1494', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1496', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1497', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1498', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1499', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1592', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1594', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1595', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1596', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1597', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1510', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1512', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1513', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1514', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1515', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1605', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1607', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1608', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1609', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1610', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1418', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1420', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1421', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1422', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1423', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1401', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1403', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1404', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1405', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1406', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1460', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1462', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1463', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1464', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1465', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1530', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1532', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1533', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1534', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1535', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1442', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1444', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1445', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1446', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1447', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1466', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1468', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1469', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1470', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1471', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1448', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1450', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1451', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1452', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1453', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1500', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1502', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1503', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1504', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1505', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1537', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1539', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1540', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1541', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1542', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1411', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1413', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1414', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1415', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1416', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1472', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1474', 'Especialidad en Ingeniería y Gestión de Proyectos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1475', 'Especialidad en Logística Internacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1477', 'Especialidad en Robótica y Manufactura');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1478', 'Especialidad en Simuladores Gráficos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1615', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1568', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1570', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1548', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1553', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1425', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1490', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1428', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1517', 'Especialidad en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1143', 'Maestría en Bioética');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1142', 'Maestría en Bioética');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1138', 'Maestría en Bioética');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1135', 'Maestría en Bioética');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1111', 'Maestría en Bioética');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1110', 'Maestría en Bioética');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1295', 'Especialidad en Psicología Clínica y Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1346', 'Especialidad en Psicología Clínica y Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1294', 'Especialidad en Psicología Clínica y Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1339', 'Especialidad en Psicología Clínica y Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1320', 'Especialidad en Psicología Clínica y Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1347', 'Especialidad en Psicología Clínica y Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1292', 'Especialidad en Psicología Clínica y Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1321', 'Especialidad en Psicología Clínica y Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1319', 'Especialidad en Psicología Clínica y Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1297', 'Especialidad en Psicología Clínica y Salud');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1041', 'Maestría en Instituciones de Derecho Financiero');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1040', 'Maestría en Instituciones de Derecho Financiero');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1307', 'Maestría en Instituciones de Derecho Financiero');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1306', 'Maestría en Instituciones de Derecho Financiero');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1305', 'Maestría en Instituciones de Derecho Financiero');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1304', 'Maestría en Instituciones de Derecho Financiero');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1584', 'Maestría en Historia del Pensamiento');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1579', 'Maestría en Historia del Pensamiento');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1581', 'Maestría en Historia del Pensamiento');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1577', 'Maestría en Historia del Pensamiento');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1580', 'Maestría en Historia del Pensamiento');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1574', 'Maestría en Historia del Pensamiento');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1265', 'Especialidad en Neuropsicología');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1264', 'Especialidad en Neuropsicología');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1191', 'Especialidad en Neuropsicología');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1269', 'Especialidad en Neuropsicología');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1326', 'Especialidad en Neuropsicología');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1267', 'Especialidad en Neuropsicología');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1395', 'Maestría en Filosofía Antigua');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1397', 'Maestría en Filosofía Antigua');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1400', 'Maestría en Filosofía Antigua');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1399', 'Maestría en Filosofía Antigua');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1398', 'Maestría en Filosofía Antigua');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1396', 'Maestría en Filosofía Antigua');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('7869', 'Especialidad en Antropología Filosófica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('7868', 'Especialidad en Antropología Filosófica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('7867', 'Especialidad en Antropología Filosófica');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1277', 'Especialidad en Psicología Organizacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1276', 'Especialidad en Psicología Organizacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1275', 'Especialidad en Psicología Organizacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1287', 'Especialidad en Psicología Organizacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1286', 'Especialidad en Psicología Organizacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1279', 'Especialidad en Psicología Organizacional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('8785', 'Maestría en Dirección de Instituciones Educativas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1194', 'Maestría en Neuropsicología y Educación');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1193', 'Maestría en Neuropsicología y Educación');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1174', 'Maestría en Neuropsicología y Educación');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1172', 'Maestría en Neuropsicología y Educación');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1192', 'Maestría en Neuropsicología y Educación');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1257', 'Maestría en Neuropsicología y Educación');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1208', 'Maestría en Neuropsicología y Educación');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1254', 'Maestría en Neuropsicología y Educación');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1441', 'Especialidad en Desarrollo del Talento Humano');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1648', 'Maestría en Derecho Constitucional y Derechos Humanos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1649', 'Maestría en Derecho Constitucional y Derechos Humanos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1647', 'Maestría en Derecho Constitucional y Derechos Humanos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1162', 'Maestría en Derecho Constitucional y Derechos Humanos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1159', 'Maestría en Derecho Constitucional y Derechos Humanos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1145', 'Maestría en Derecho Constitucional y Derechos Humanos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1153', 'Maestría en Derecho Constitucional y Derechos Humanos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1467', 'Maestría en Derecho de la Empresa');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1005', 'Maestría en Derecho de la Empresa');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1274', 'Maestría en Derecho de la Empresa');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1004', 'Maestría en Derecho de la Empresa');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1465', 'Maestría en Derecho de la Empresa');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1003', 'Maestría en Derecho de la Empresa');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1463', 'Maestría en Derecho de la Empresa');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1266', 'Maestría en Derecho de la Empresa');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1262', 'Maestría en Derecho de la Empresa');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1578', 'Maestría en Derecho Procesal Constitucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1324', 'Maestría en Derecho Procesal Constitucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1322', 'Maestría en Derecho Procesal Constitucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1323', 'Maestría en Derecho Procesal Constitucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1325', 'Maestría en Derecho Procesal Constitucional');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1298', 'Maestría en Derecho Fiscal');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1296', 'Maestría en Derecho Fiscal');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1281', 'Maestría en Derecho Fiscal');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1280', 'Maestría en Derecho Fiscal');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1340', 'Maestría en Derecho Administrativo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1342', 'Maestría en Derecho Administrativo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1343', 'Maestría en Derecho Administrativo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1341', 'Maestría en Derecho Administrativo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1328', 'Maestría en Derecho Administrativo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1327', 'Maestría en Derecho Administrativo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1557', 'Doctorado en Derecho');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1547', 'Doctorado en Derecho');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1233', 'Doctorado en Derecho');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1207', 'Maestría en Ciencias Jurídicas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1203', 'Maestría en Ciencias Jurídicas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1200', 'Maestría en Ciencias Jurídicas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1198', 'Maestría en Ciencias Jurídicas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1197', 'Maestría en Ciencias Jurídicas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1196', 'Maestría en Ciencias Jurídicas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11723', 'Maestría en Gestión y Operación de establecimiento de Alimentos y Bebidas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1529', 'Maestría en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1622', 'Maestría en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1526', 'Maestría en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1614', 'Maestría en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1509', 'Maestría en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1619', 'Maestría en Dirección de Operaciones');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('5587', 'Doctorado en Historia del pensamiento');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('5585', 'Doctorado en Historia del pensamiento');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('5583', 'Doctorado en Historia del pensamiento');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('5582', 'Doctorado en Historia del pensamiento');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11691', 'Maestría en Relaciones Públicas y Gestión de eventos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11688', 'Maestría en Relaciones Públicas y Gestión de eventos');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('11539', 'Esp. en Publicidad y Relaciones Públicas');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1366', 'Maestría en Terapia de Heridas, Estomas y Quemaduras');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1363', 'Maestría en Terapia de Heridas, Estomas y Quemaduras');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1364', 'Maestría en Terapia de Heridas, Estomas y Quemaduras');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1180', 'Maestría en Terapia de Heridas, Estomas y Quemaduras');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1179', 'Maestría en Terapia de Heridas, Estomas y Quemaduras');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1189', 'Especialidad en Terapia de Heridas, Estomas y Quemaduras');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1187', 'Especialidad en Terapia de Heridas, Estomas y Quemaduras');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1188', 'Especialidad en Terapia de Heridas, Estomas y Quemaduras');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1185', 'Especialidad en Terapia de Heridas, Estomas y Quemaduras');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1183', 'Especialidad en Terapia de Heridas, Estomas y Quemaduras');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('10826', 'Doctorado en Derecho');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1080', 'Especialidad en Derecho Procesal Civil y Mercantil');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1068', 'Especialidad en Derecho Procesal Civil y Mercantil');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1067', 'Especialidad en Derecho Procesal Civil y Mercantil');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1066', 'Especialidad en Derecho Procesal Civil y Mercantil');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1065', 'Especialidad en Derecho Procesal Civil y Mercantil');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1064', 'Especialidad en Derecho Procesal Civil y Mercantil');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1063', 'Especialidad en Derecho Procesal Civil y Mercantil');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1141', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1140', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1139', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1138', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1137', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1136', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1243', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1153', 'Especialidad en Instituciones de Derecho Mercantil');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1152', 'Especialidad en Instituciones de Derecho Mercantil');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1151', 'Especialidad en Instituciones de Derecho Mercantil');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1242', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1241', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1240', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1239', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1237', 'Especialidad en Derecho de Amparo');
INSERT INTO Clase_programa (no_clase, programa) VALUES ('1236', 'Especialidad en Derecho de Amparo');
