INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1229',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1230',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1231',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1232',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1217',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1218',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1219',3);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1220',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1082',19);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1083',19);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1168',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Administración de Proyectos', '1084',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1112',24);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1118',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1221',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1173',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1175',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1116',11);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1113',24);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1119',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1209',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1170',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1171',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1126',11);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1117',24);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1115',8);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1114',8);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Finanzas', '1124',8);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1149',17);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1133',6);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1222',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1223',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1224',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1128',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1210',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1211',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1212',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1129',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1160',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1130',17);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1147',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Impuestos', '1132',8);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1225',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1226',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1227',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1228',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1213',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1214',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1215',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1216',5);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1086',8);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1088',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1102',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Mercadotecnia Estratégica', '1098',4);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Negocios Internacionales', '1109',0);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Negocios Internacionales', '1101',0);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Negocios Internacionales', '1103',0);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Negocios Internacionales', '1165',0);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Negocios Internacionales', '1161',2);
