INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', '1235',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '1455',8);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '1448',8);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '10418',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '241152',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '174631',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '10419',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '10439',10);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '6651',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '10947',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '10948',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '10949',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '10950',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '10951',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '10952',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '10954',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Maestría en Dirección de Instituciones de Salud', '10975',7);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '6652',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '6653',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '6654',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '6655',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '6656',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '6657',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '6650',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '1384',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '1386',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '1388',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '1389',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '1390',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '1391',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '1392',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Gestión de Eventos', '1393',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', '1374',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', '1378',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', '1379',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', '1380',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', '1381',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', '1382',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', '1383',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Diplomado en Wellness', 'SESI',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Diplomado en Wellness', 'DIME',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Diplomado en Wellness', 'DIMFI',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Diplomado en Wellness', 'DIMAM',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Diplomado en Wellness', 'DIMIN',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Diplomado en Wellness', 'DIMESP',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Diplomado en Wellness', 'DIMSOC',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Diplomado en Wellness', 'DIMFIN',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Diplomado en Wellness', 'DIMOC',15);
INSERT INTO Clase_programa (programa, no_clase,num_alunos) VALUES ('Diplomado en Wellness', 'IWV',15);
