UPDATE Programa SET cuenta='13023113' where programa = 'Especialidad en Derecho de Amparo';
UPDATE Programa SET cuenta='13023113' where programa = 'Especialidad en Derecho de la Empresa';
UPDATE Programa SET cuenta='13023113' where programa = 'Especialidad en Derecho de la Empresa';
UPDATE Programa SET cuenta='13023113' where programa = 'Especialidad en Derecho de la Empresa';
UPDATE Programa SET cuenta='13023113' where programa = 'Especialidad en Derecho de la Empresa';
UPDATE Programa SET cuenta='13023113' where programa = 'Especialidad en Derecho de la Empresa';
UPDATE Programa SET cuenta='13023113' where programa = 'Especialidad en Derecho de la Empresa';
UPDATE Programa SET cuenta='13023113' where programa = 'Especialidad en Derecho de la Empresa';
UPDATE Programa SET cuenta='13023113' where programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Ciencias Jurídicas';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Ciencias Jurídicas';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Ciencias Jurídicas';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Ciencias Jurídicas';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Ciencias Jurídicas';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Ciencias Jurídicas';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Ciencias Jurídicas';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Administrativo';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Administrativo';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Administrativo';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Administrativo';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Administrativo';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Administrativo';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Administrativo';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Administrativo';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Administrativo';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Administrativo';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Fiscal';
UPDATE Programa SET cuenta='13024116' where programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Programa SET cuenta='13024116' where programa = 'Maestría en Derecho de la Empresa';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Laboral';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Laboral';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Laboral';
UPDATE Programa SET cuenta='13023113' where programa = 'Maestría en Derecho Laboral';
UPDATE Programa SET cuenta='13023113' where programa = 'Doctorado en Derecho';
UPDATE Programa SET cuenta='13023113' where programa = 'Doctorado en Derecho';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Administración de Proyectos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Administración de Proyectos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Administración de Proyectos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Administración de Proyectos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Administración de Proyectos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Administración de Proyectos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Administración de Proyectos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Administración de Proyectos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Finanzas';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Finanzas';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Finanzas';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Finanzas';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Finanzas';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Finanzas';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Finanzas';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Finanzas';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Finanzas';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Mercadotecnia Estratégica';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Mercadotecnia Estratégica';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Mercadotecnia Estratégica';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Mercadotecnia Estratégica';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Mercadotecnia Estratégica';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Mercadotecnia Estratégica';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Mercadotecnia Estratégica';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Mercadotecnia Estratégica';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Mercadotecnia Estratégica';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Mercadotecnia Estratégica';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Mercadotecnia Estratégica';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Negocios Internacionales';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Negocios Internacionales';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Negocios Internacionales';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Negocios Internacionales';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Negocios Internacionales';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Negocios Internacionales';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Negocios Internacionales';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Impuestos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Impuestos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Impuestos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Impuestos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Impuestos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Impuestos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría en Impuestos';
UPDATE Programa SET cuenta='12011101' where programa = 'Maestría Internacional en Finanzas';
UPDATE Programa SET cuenta='12011101' where programa = 'Doctorado en Ciencias Empresariales';
UPDATE Programa SET cuenta='12011101' where programa = 'Doctorado en Ciencias Empresariales';
UPDATE Programa SET cuenta='12011101' where programa = 'Doctorado en Ciencias Empresariales';
UPDATE Programa SET cuenta='12054105' where programa = 'Diplomado Wellness';
UPDATE Programa SET cuenta='12054104' where programa = 'Especialidad en Emprendedores de Negocios de Alimentos y Bebidas';
UPDATE Programa SET cuenta='12054104' where programa = 'Especialidad en Emprendedores de Negocios de Alimentos y Bebidas';
UPDATE Programa SET cuenta='12054103' where programa = 'Especialidad en Gestión de Eventos';
UPDATE Programa SET cuenta='12054103' where programa = 'Especialidad en Gestión de Eventos';
UPDATE Programa SET cuenta='12054103' where programa = 'Especialidad en Gestión de Eventos';
UPDATE Programa SET cuenta='12054103' where programa = 'Especialidad en Gestión de Eventos';
UPDATE Programa SET cuenta='12054103' where programa = 'Especialidad en Gestión de Eventos';
UPDATE Programa SET cuenta='12054105' where programa = 'Maestría en Dirección de Instituciones de Salud';
UPDATE Programa SET cuenta='12054105' where programa = 'Maestría en Dirección de Instituciones de Salud';
UPDATE Programa SET cuenta='13064103' where programa = 'Maestría en Historia del Pensamiento';
UPDATE Programa SET cuenta='14033103' where programa = 'Optativas';
UPDATE Programa SET cuenta='14033103' where programa = 'Optativas';
UPDATE Programa SET cuenta='14033103' where programa = 'Optativas';
UPDATE Programa SET cuenta='14033103' where programa = 'Optativas';
UPDATE Programa SET cuenta='14033103' where programa = 'Optativas';
UPDATE Programa SET cuenta='14033103' where programa = 'Optativas';
UPDATE Programa SET cuenta='14033103' where programa = 'Optativas';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Logística Internacional';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Logística Internacional';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Logística Internacional';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Logística Internacional';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Robótica y Manufactura';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Robótica y Manufactura';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Simuladores Gráficos';
UPDATE Programa SET cuenta='14033103' where programa = 'Especialidad en Simuladores Gráficos';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ciencia de Datos';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ciencia de Datos';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Dirección de Operaciones';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Programa SET cuenta='14033103' where programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Programa SET cuenta='14033103' where programa = 'Doctorado en Inteligencia Artificial';
UPDATE Programa SET cuenta='14033103' where programa = 'Doctorado en Inteligencia Artificial';
UPDATE Programa SET cuenta='13043108' where programa = 'Especialidad en Desarrollo del Talento Humano';
UPDATE Programa SET cuenta='13044104' where programa = 'Maestría en Dirección de Capital Humano';
UPDATE Programa SET cuenta='13044104' where programa = 'Maestría en Dirección de Capital Humano';
UPDATE Programa SET cuenta='13044104' where programa = 'Maestría en Dirección de Capital Humano';
UPDATE Programa SET cuenta='13044111' where programa = 'Maestría en Dirección de Instituciones Educativas';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Publicidad y Creación de Contenidos';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Publicidad y Creación de Contenidos';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Publicidad y Creación de Contenidos';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Publicidad y Relaciones Públicas';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Publicidad y Relaciones Públicas';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Publicidad y Relaciones Públicas';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Publicidad y Relaciones Públicas';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Publicidad y Relaciones Públicas';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Publicidad y Relaciones Públicas';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Publicidad y Relaciones Públicas';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Publicidad y Relaciones Públicas';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Relaciones Públicas y Reputación de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Relaciones Públicas y Reputación de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Relaciones Públicas y Reputación de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Relaciones Públicas y Reputación de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Relaciones Públicas y Reputación de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Relaciones Públicas y Reputación de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Relaciones Públicas y Reputación de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Relaciones Públicas y Reputación de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Especialidad en Relaciones Públicas y Reputación de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicaciones de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicaciones de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicaciones de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicaciones de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicaciones de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicaciones de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicaciones de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicaciones de Marca';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Institucional';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Narrativa y Producción Audiovisual';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Narrativa y Producción Audiovisual';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Narrativa y Producción Audiovisual';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Narrativa y Producción Audiovisual';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Narrativa y Producción Audiovisual';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Narrativa y Producción Audiovisual';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Narrativa y Producción Audiovisual';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Narrativa y Producción Audiovisual';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Narrativa y Producción Audiovisual';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Narrativa y Producción Audiovisual';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Política y Pública';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Política y Pública';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Política y Pública';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Política y Pública';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Política y Pública';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Política y Pública';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Política y Pública';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Política y Pública';
UPDATE Programa SET cuenta='13014101' where programa = 'Maestría en Comunicación Política y Pública';

