INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('gmoreno@up.edu.mx', 'Guadalupe Moreno Toscano', '6659', '19/07');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('gpliego@up.edu.mx', 'Gabriel Pliego Araujo', '6650', '22/01');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('belopez@up.edu.mx', 'Blanca Estela López Hernández', '5626', '16/04');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('cvillanuevas@up.edu.mx', 'Claudia Villanueva Saenz', '23/10');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('gcantu@up.edu.mx', 'Guillermo Cantú Quintanilla', '5646', '14/12');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('gobrador@up.edu.mx', 'Gregorio Obrador Vera', '5654', '26/01');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('ijuarez@up.edu.mx', 'Irina Elizabeth Juárez Muñoz', '5668', '11/01');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('anherrera@up.edu.mx', 'Andrea Herrera García', '5634', '25/06');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('alopezm@up.edu.mx', 'Adriana López Morales', '6154', '20/06');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('gsierrap@up.edu.mx', 'Gabriela Sierra Pérez', '6129', '25/12');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('jrincon@up.edu.mx', 'Juan Andrés Rincón-González', '6142', '02/06');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('lgarduno@up.edu.mx', 'Laura Mariana Garduño Espinosa', '6197', '13/05');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('mnavarroa@up.edu.mx', 'Mariano Emmanuel Navarro Arroyo', '6154', '24/07');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('sbarquet@up.edu.mx', 'Stephanie Barquet Nemer', '6192', '18/06');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('agonzalezar@up.edu.mx', 'Adriana González Arce', '5127', '01/12');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('cpreciado@up.edu.mx', 'Carlos Preciado Pardinas', '5119', '06/11');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('fbatista@up.edu.mx', 'Fernando Batista Jiménez', '5132', '20/12');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('gtejeda@up.edu.mx', 'Guillermo Tejeda Becerra', '5177', '25/07');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('hsramire@up.edu.mx', 'Hugo Saúl Ramírez García', '5160', '20/03');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('idelrio@up.edu.mx', 'Ivonne del Río Galindo', '5183', '19/05');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('jfdiez@up.edu.mx', 'Juan Francisco Diez Spelz', '5115', '23/10');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('jmacuna@up.edu.mx', 'Juan Manuel Acuña Roldán', '03/12');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('jmaotero@up.edu.mx', 'Juan Manuel Otero', '5184', '27/10');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('mbartolini@up.edu.mx', 'Marcelo Bartolini Esparza', '16/12');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('omejia@up.edu.mx', 'Olimpia Mejía Ayala', '5173', '16/10');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('mrs@up.edu.mx', 'Miriam Rodríguez Sánchez', '5181', '29/04');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('bherjua@up.edu.mx', 'Brenda Cecilia Hernández Juárez', '5176', '15/11');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('amarcial@up.edu.mx', 'Andrés Marcial Nieto', '5182', '30/11');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('irebollar@up.edu.mx', 'Iranzú Rebollar Lázaro', '20/03');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('peruizba@up.edu.mx', 'Pilar Ruíz Becerra', '5704', '25/09');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('aarceopa@up.edu.mx', 'Angélica Arceo Pantoja', '5152', '28/11');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('jcasanovas@up.edu.mx', 'Juan Antonio Casanovas Esquivel', '15/05');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('kfranck@up.edu.mx', 'Karla Yolanda Franck Galindo', '5133', '08/05');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('mgarcia@up.edu.mx', 'Marcelo García Ramírez', '29/10');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('aalegriay@up.edu.mx', 'Alma Alegría Ysunza', '5462', '14/05');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('dlopezm@up.edu.mx', 'Daniela López Martínez', '5465', '24/05');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('dortiz@up.edu.mx', 'Daniel Ortiz Otegui', '5020', '08/08');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('eugonzal@up.edu.mx', 'Eulalio González Anta', '5400', '03/08');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('mpaniagu@up.edu.mx', 'Miriam Paniagua Pinto', '5040', '31/05');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('ndiaz@up.edu.mx', 'Natalia Díaz Ibarrola', '5461', '14/12');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('rguzman@up.edu.mx', 'Regina Guzmán Montiel', '5426', '10/09');
INSERT INTO Personas (email_persona, nombre, ext) VALUES ('dscasillas@up.edu.mx', 'Daniel Sebastián Casillas Giralt', '5031.0');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('amgarciac@up.edu.mx', 'Amelia García Casas', '8123', '01/09');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('jtronp@up.edu.mx', 'Jacqueline Tron Pérez', '8169', '07/02');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('lpfernandez@up.edu.mx', 'Laura Patricia Fernández Arreola', '8175', '04/06');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('mbasurto@up.edu.mx', 'Mariana Basurto Félix', '02/06');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('vroarof@up.edu.mx', 'Verónica Roaro Fuentes', '8173', '12/05');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('jgarciac@up.edu.mx', 'Jovanna Ingrid García Calzón', '22/03');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('mepelaez@up.edu.mx', 'María Elena García Peláez Cruz', '5315', '25/12');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('mlecon@up.edu.mx', 'Mauricio Lecón Rosales', '5325', '17/06');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('cgherrera@up.edu.mx ', 'Carlos Gerardo Herrera Mendiolea', '5856', '03/03');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('fgamboa@up.edu.mx', 'Francisco Gamboa Barrón', '5857', '31/01');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('gtenorio@up.edu.mx', 'Guillermo Antonio Tenorio Cueto', '5186', '27/08');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('hcasillas@up.edu.mx', 'Héctor Samuel Casillas Martínez', '12/05');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('rmartinezm@up.edu.mx', 'Hiram Martínez y Martínez', '5866', '04/01');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('aordonet@up.edu.mx', 'Alejandro Ordóñez Torres', '5200', '11/07');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('caperez@up.edu.mx ', 'Andrómeda Pérez Sagredo', '6829', '12/08');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('cwelsh@up.edu.mx', 'Carlos Gerardo Welsh Vota', '06/01');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('fcal@up.edu.mx', 'Francisco Cal y Mayor Peña', '07/10');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('laberumen@up.edu.mx', 'Lorena Alexandra Berumen Glinz', '5247', '18/12');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('mhurtado@up.edu.mx', 'Margarita Hurtado Hernández', '6831', '01/06');
INSERT INTO Personas (email_persona, nombre, birthday) VALUES ('ssanchez@up.edu.mx', 'Susana Sánchez Vizcaya', '08/09');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('imoya@up.edu.mx', 'Isabel Moya Gómez Verea', '6622', '16/12');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('jcobela@up.edu.mx', 'José Francisco Cobela Vargas', '5371', '19/03');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('ltovar@up.edu.mx', 'Luis Enrique Tovar Ávila', '5317', '11/11');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('mejimene@up.edu.mx', 'Margarita Espinosa Jiménez', '5361', '01/09');
INSERT INTO Personas (email_persona, nombre, ext,birthday) VALUES ('mvillarreal@up.edu.mx', 'Mónica Adriana Villarreal García', '5367', '07/07');




INSERT INTO Personas (email_persona, nombre) VALUES ('dduarte@up.edu.mx', 'Daniel Duarte Reyes');
INSERT INTO Personas (email_persona, nombre) VALUES ('tsepulve@up.edu.mx', 'Teresa Eugenia Sepulveda');
INSERT INTO Personas (email_persona, nombre) VALUES ('jjvargas@up.edu.mx', 'Juan Jesus Vargas Velázquez');
INSERT INTO Personas (email_persona, nombre) VALUES ('gechevarria@up.edu.mx', 'Gustavo Echevarría Navarro');
INSERT INTO Personas (email_persona, nombre) VALUES ('mjimenez@up.edu.mx', 'Monica Angélica Jiménez Almanza');
INSERT INTO Personas (email_persona, nombre) VALUES ('bdupre@up.edu.mx', 'Bertha Maria Dupré Pérez');
INSERT INTO Personas (email_persona, nombre) VALUES ('cdejesus@up.edu.mx', 'Carolina de Jesús Betancourt');
INSERT INTO Personas (email_persona, nombre) VALUES ('emorales@up.edu.mx', 'Edgar Omar Morales Contreas');
INSERT INTO Personas (email_persona, nombre) VALUES ('arlimas@up.edu.mx', 'Alma Rosa Limas Álvaréz');
INSERT INTO Personas (email_persona, nombre) VALUES ('gtorresm@up.edu.mx', 'Georgina Torres Mondragón');
INSERT INTO Personas (email_persona, nombre) VALUES ('farteagar@up.edu.mx', 'Frida Angélica Arteaga Rodríguez');
INSERT INTO Personas (email_persona, nombre) VALUES ('ggalvan@up.edu.mx', 'Gerogina Galván Rodríguez');
INSERT INTO Personas (email_persona, nombre) VALUES ('ejimeneza@up.edu.mx', 'Elizabeth Jiménez Almanza');
INSERT INTO Personas (email_persona, nombre) VALUES ('crohde@up.edu.mx', 'Carolina Rohde Faraude');
INSERT INTO Personas (email_persona, nombre) VALUES ('jpardo@up.edu.mx', 'José Mauricio Pardo Benito');
INSERT INTO Personas (email_persona, nombre) VALUES ('olozada@up.edu.mx', 'Octavio Lozada Flores');
INSERT INTO Personas (email_persona, nombre) VALUES ('hponce@up.edu.mx', 'Hiram Eredin Ponce Espinosa');
