INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031426','Curaduría y Museografía en las');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031429','Conservación y Gestión del Pat');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031434','Políticas Culturales Comparada');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031422','Comunicación y Mercadotecnia C');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031433','Gestión Gubernamental y Diseño');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031435','Diplomacia Cultural');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031431','Creación de Empresas y Emprend');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031432','Administración del Capital Hum');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031430','Gestión de Organizaciones Cult');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031427','Programación y Gestión de las');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031423','Marco Legal y Jurídico');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031428','Producción e Industria Cinemat');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035257','Estrategia de Comunicación y P');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035259','Datos e Inteligencia del Consu');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035270','Economía del Comportamiento');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035263','Principios de Automatización e');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035269','Comunicación de Crisis');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035271','Modelos de Análisis, Medición');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035273','Privacidad y Uso de Datos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('015573','Manejo de Crisis y Negociación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035265','Ética de la Comunicación para');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035274','Comunicación Ética para el Cam');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035275','Estrategia de Comunicación y P');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035291','Datos e Inteligencia del Consu');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035281','Economía del Comportamiento');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035289','Principios de Automatización e');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035280','Comunicación de Crisis');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035288','Modelos de Análisis, Medición');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035290','Privacidad y Uso de Datos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032688','Manejo de Big Data');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032686','Comunicación Financiera');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032713','Desarrollo de Contenidos Audio');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032683','Seminario de Titulación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032665','Comunicación Integrada');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032687','Comunicación Directiva');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032723','Seminario de Titulación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032716','Procesos de Producción');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032717','Paradigmas Artísticos en el D');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032681','Comunicación en Situaciones de');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032682','Ética de la Comunicación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032722','Ética de la Comunicación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035286','Ética de la Comunicación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032667','Diseño y Gestión de Contenidos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032694','Opinión Pública y Comunicación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035287','Seminario de Titulación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032707','Nuevas Narrativas Audiovisuale');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032709','Ética de la Comunicación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032710','Seminario de Titulación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032695','Comunicación y Persuasión');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032696','Estrategias para Campañas Polí');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032700','Diplomacia Pública y Cultural');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032714','Empresa Audiovisual y Marco No');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009840','La Jurisprudencia');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('010128','Temas Selectos de Derecho Proc');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009809','Derecho Bancario');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009833','Las Sentencias y los Recursos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('010092','La Acción Procesal');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('010115','Juicio Ordinario. Fase Probato');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009811','Derecho Bursátil');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009839','Amparo Agrario');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009740','Diversas Cuestiones Procesales');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('010114','Juicio Ordinario. Introducción');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009741','Improcedencia y Sobreseimiento');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009813','Contratación por Medios Electr');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009837','Amparo Laboral');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009836','Amparo Penal');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('010091','Introducción al Derecho Proces');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009739','La Suspensión del Acto Reclama');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009736','Teoría del Proceso');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009838','Amparo Administrativo y Fiscal');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009841','Seminario de Temas Selectos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('010113','Jurisdicción');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009738','Control y Defensa de la Consti');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('009734','Introducción al Juicio de Ampa');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('010116','Juicio Ordinario. Fase Conclus');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027442','Operaciones Bancarias y Temas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031499','Conceptos Fundamentales del D');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024281','Interpretación y Argumentación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024259','Función Pública');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027441','El Sistema Financiero y Banca');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('021373','Filosofía del Derecho');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024303','Interpretación y Argumentación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024298','Seminario de Toma de Decisione');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024286','Procesos Constitucionales');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024307','Sistema Internacional y Region');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024263','Servicios Públicos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024270','Conceptos Fundamentales de Der');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('021369','Metodología del Derecho');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('021376','Seminario de Investigación y T');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024274','Procedimiento Contencioso Adm.');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024282','Fundamentos de Derecho Procesa');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031501','Derecho Colectivo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('021380','Temas Selec de Teoría Política');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024297','Etapa de Transf. de la Empresa');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024271','Procedimientos Administrativos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027439','Principios Éticos del Derecho');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024308','Protección y Promoción de los');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024276','Seminario de Temas de Fiscali');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024266','Temas Selectos de Derecho Admi');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027440','Economía y Derecho Monetario');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024294','Etapa de Creación de la Empres');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031503','Derecho Procesal del Trabajo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031500','Conceptos Fundamentales del D');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024258','Fundamentos de Derecho Adminis');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024302','Seminario de Investigación y T');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024280','Seminario de Investigación y T');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('021370','Antropología y Ética');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024299','Empresa y Familia');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024293','Se Metodología Estudio de Caso');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027453','Organizaciones y Actividades A');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031502','Relaciones Individuales del T');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024283','Fundamentos Constitucionales');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024269','Temas Selectos de Administraci');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024268','Temas Selectos de Derecho Admi');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024304','Fundamentos Histórico Filosófi');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027454','Productos Financieros Derivado');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024306','Fundamentos Constitucionales');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('021371','Historia del Pensamiento Juríd');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024309','Seminario de Temas Selectos de');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031513','Seminario de Actualización en');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('023123','Seminario de Investigación IV');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('023120','Seminario de Investigación I');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('010309','Antropología y Ética');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('023124','Seminario de Investigación V');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032425','Organizaciones Ambidiestras');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032556','Organizaciones Ambidiestras');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032541','Organizaciones Ambidiestras');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032427','Big Data y Megatendencias');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032558','Big data y Megatendencias');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032543','Big data y Megatendencias');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032426','Metodologías Ágiles para la In');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032557','Metodologías Ágiles para la In');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032542','Metodologías Ágiles para la In');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032413','Ética Empresarial y Resp. Soc.');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032490','Ética Empresarial y Responsabi');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032506','Ética Empresarial y Responsabi');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032544','Ética Empresarial y Responsabi');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032414','Dirección Estratégica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032491','Dirección Estratégica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032507','Dirección Estratégica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032545','Dirección Estratégica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030389','Información financiera y proce');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032513','Aspectos Internacionales de lo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032508','Política Fiscal y Marco Tribut');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032521','Análisis Comparativo del ISR');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032555','Nuevos Modelos de Mercadotecni');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030403','Talento y su dinámica dentro');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032551','Gestión de Relación con los Cl');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032548','Gestión Estratégica de Precios');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032516','Aspectos Fiscales del Comercio');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032547','Marcas y Posicionamiento');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030394','Estrategia corporativa y relac');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030408','Cumplimiento y control normati');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032519','Precios de Transferencia');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032518','Introducción a la Tributación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030391','Administración de Riesgos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030395','Ética y responsabilidad empres');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032510','Impuestos Indirectos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032500','Valuación de Instrumentos Deri');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030386','Nuevas alternativas de inversi');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032503','Tesorería y Sistema Bancario');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032501','Administración de Portafolios');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032514','Regímenes Especiales de ISR');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032504','Impuestos Corporativos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032511','Impuestos Corporativos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030409','Coordinación y formación de su');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032493','Métodos Cuantitativos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032505','Derecho Corporativo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032509','ISR Personas Morales');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032515','Contribuciones del Trabajo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030393','Finanzas Internacionales');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030390','Mercados financieros');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030392','Oportunidades globales y entor');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032553','Evolución de la Mercadotecnia');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032512','ISR Personas Físicas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032517','Procedimientos Administrativos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032520','Gestión Tributaria Internacion');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032419','Impactos Organizacionales y Cu');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032421','Ejecución de la Estrategia y D');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032423','Habilidades Interpersonales pa');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032424','Seminario de Casos de Negocio');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032418','Gestión de Riesgos en Proyecto');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032420','Finanzas en la Organización');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032417','Técnicas y Herramientas para');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032422','Seminario de preparación para');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032415','Fundamentos de la Administraci');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032416','Oficina de Dirección de Proyec');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032502','Control Interno, Costos y Pres');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032496','Analítica de Datos Financieros');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032497','Finanzas Corporativas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032492','Entorno Económico');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032494','Contabilidad Financiera');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032495','Análisis Financiero');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032498','Valuación de Instrumentos de R');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032499','Valuación de Instrumentos de R');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030404','Seminario de innovación financ');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032554','Inteligencia de Negocios en un');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032549','Comunicaciones Integrales de M');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032550','Análisis Financiero de la Merc');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032552','Gestión Estratégica de Ventas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032546','Investigación de Mercados');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032536','Formas de Pago Internacional');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032537','Contratos Internacionales');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032534','Negocios Internacionales de Se');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032538','Transporte Internacional de Me');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032539','Marco Regulatorio del Comercio');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('032540','Aspectos Estratégicos del Proc');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028749','Seminario de Investigación IV');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028746','Seminario de Investigación II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031569','Propedéutico en Economía');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028745','Métodos Cuantitativos Multiva.');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028751','Seminario de Investigación VI');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028740','Inteligencia de Negocios');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031570','Propedéutico en Estadística');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028741','Finanzas Corporativas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031571','Propedéutico en Finanzas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031515','Análisis de Riesgos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028742','Métodos Cualitativos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031521','Temas Avanzados de Estrategia');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('031518','Mercadotecnia Analítica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('015285','Heridas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('015286','Quemaduras');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('015287','Disfunción del piso pélvico');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('015288','Ostomías, Fístulas y Drenajes');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('015291','Disfunción del piso pélvico');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('015289','Heridas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('015290','Quemaduras');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('015292','Ostomías, Fístulas y Drenajes');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029295','Control Financiero');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029476','Plan de operación de negocios');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029483','Servicio de alimentos y bebida');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029289','Emprendimiento e Innovación en');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029290','Merca enfocada a la industria');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029479','Relaciones públicas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029478','Logística, compra y operación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029475','Introducción y planeación de');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029477','Mercadotecnia de servicios');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('019928','Control Financiero');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('019016','Control de Recursos Financiero');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('019019','Servicio de Alimentos y Bebida');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028941','Hospitalidad en las institucio');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028949','Seguridad dentro de las instal');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028942','Administración Financiera');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028947','Servicios generales');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028945','Marco legal aplicado');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028950','El servicio de alimentos:');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028951','Bioética');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026222','Antropología Teológica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026221','Racionalidad y Transcendencia');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026220','Formación Humana e Intersubjet');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026821','Introducción a la Traducción');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026819','Introducción al Griego Clásico');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027313','Temas Selec de Hist. Ideas I');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027311','Temas Select. de Filosofía III');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026824','Propedéutica de la Investigaci');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026830','Seminario de Investigación y T');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026851','Temas Selectos de Filosofía Na');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027315','Temas Selec de Hist. Ideas III');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027307','Historia de la Cultura Moderna');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027309','Temas Selectos de Filosofía I');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026842','Seminario Sobre la Recepción Á');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027262','Historia de la Cultura Antigua');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('019324','Sem. de Inv. y Tutoría III');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('019325','Sem. de Inv. y Tutoría IV');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('019322','Sem. de Inv. y Tutoría I');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('019323','Sem. de Inv. y Tutoría II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028769','Financiamiento del delito y su');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030413','Finanzas Públicas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030417','Políticas Públicas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028768','Políticas Públicas y combate a');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028774','Fiscalización y rendición de');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('030418','Política y toma de decisiones');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028771','Temas selectos de prevención y');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027895','Análisis de Grandes Volúmenes');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029228','Análisis de Grandes Volúmenes');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027907','Gestión del cambio');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027891','Monetización de la Innovación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029224','Monetización de la Innovación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027896','Planeación estratégica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029229','Planeación estratégica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027886','Sistemas de ayuda a la decisió');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027885','Administración de los Sistemas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027914','Comercio electrónico y estánda');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027904','Ingeniería de Proyectos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029218','Materiales y Procesos para la');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027923','Procesadores Gráficos y Aplica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028053','Selección de Materiales para');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027894','Aprendizaje Automático');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029227','Aprendizaje Automático');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027893','Inteligencia de Negocio y Solu');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029226','Inteligencia de Negocio y Solu');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027899','Temas selectos de Innovación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029232','Temas selectos de Innovación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029216','Análisis de Ciclo de Vida');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027915','Diseño de CDCs y Almacenes');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027925','Dispositivos Hápticos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028054','Integración Mecatrónica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027898','Análisis de Factores Sociales,');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029231','Análisis de Factores Sociales,');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027892','Diseño y venta de propuestas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029225','Diseño y venta de propuestas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027897','Liderazgo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029230','Liderazgo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027906','Ejecución, control y cierre op');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027887','Ejecución, medición y control');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027916','Optimización de la Cadena de S');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027924','Reconocimiento de Señales');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028055','Robótica y Programación Indust');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029220','Tendencias tecnológicas para');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027888','Dirección estratégica disrupti');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027908','Dirección estratégica disrupti');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027917','Dirección estratégica disrupti');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027901','Humanismo contemporáneo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029234','Humanismo Contemporáneo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027889','Administración de recursos hum');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029221','LEED GA');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027909','Curso de preparación para Cert');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027918','Satisfacción del cliente');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028056','Modelos Computacionales para');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027930','Temas selectos de Simuladores');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027957','Gestión del cambio');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029563','Monetización de la Innovación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029559','Planeación estratégica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028717','Sistemas de ayuda a la decisió');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027938','Sistemas de ayuda la decisión');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028716','Administración de los Sistemas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027937','Administración de los Sistemas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028724','Comercio electrónico y estánda');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027946','Comercio electrónico y estánda');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027954','Ingeniería de Proyectos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027995','Materiales y Procesos para la');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027974','Procesadores Gráficos y Aplica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027964','Selección de Materiales para');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027991','Análisis de Ciclo de Vida');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028725','Diseño de CDCs y Almacenes');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027947','Diseño de CDCs y Almacenes');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027976','Dispositivos Hápticos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027965','Integración Mecatrónica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029561','Análisis de Factores Sociales,');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029564','Diseño y venta de propuestas');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('019629','Seminario de Investigación I');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028710','Estadística Investigación');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027931','Estadística para la Investigac');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029560','Liderazgo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('019630','Seminario de Investigación II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028711','Seminario de Investigación I');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027932','Seminario de Investigación I');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('019631','Seminario de Tesis');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028712','Seminario de Investigación II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027933','Seminario de Investigación II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027956','Ejecución, control y cierre op');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028718','Ejecución, medición y control');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027939','Ejecución, medición y control');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('028726','Optimización de la Cadena de S');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027948','Optimización de la Cadena de S');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027975','Reconocimiento de Señales');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027966','Robótica y Programación Indus');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027993','Tendencias tecnológicas para');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029565','Humanismo contemporáneo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029544','Fundamentos de Ciencia de Dato');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029545','Estadística');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029553','Proyecto de Aplicación de Cien');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029554','Minería de Datos y Redes Socia');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029555','Principios de Aprendizaje Prof');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029558','Fundamentos de Bases de Datos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029549','Ética de Ciencia de Datos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029543','Aprendizaje de Máquina I');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029548','Visualización de Datos y Narra');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029551','Gobierno y Protección de Datos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029552','Cómputo en la Nube');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029557','Grandes Datos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027760','Metodología de la Inv. I');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027756','Bioética y Derecho Biojurídica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027757','Nociones de Ética');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027759','Taller de Recursos Argumentati');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027758','Bioética y Ética de Medicina');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027755','Bases del Pensamiento');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029587','Sem. Interdis. de Bioética IV');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029586','Seminario de Inv. IV');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('029599','Bioética en la Farmacogenética');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024763','Formación por competencias');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024774','Currículo e inclusión educativ');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024770','Procesos de memoria y aprendiz');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024780','Funcionalidad visual y eficaci');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035053','Atracción, Retención y Desarro');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024769','Lateralidad y rendimiento esco');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024775','Dislexia, hiperactividad y dis');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035064','Relaciones Laborales y Segurid');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024777','Atención a los alumnos con tal');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035059','Evaluación del Capital Humano');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035068','Comunicación Organizacional');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035056','Formación del Talento Humano');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035060','Dirección Estratégica');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035061','Gestión del Cambio');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035065','Persona, Organización y Cultur');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035071','Analítica de Datos');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035057','Competencias Directivas y de L');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035063','Control Integral del Talento H');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('035335','Temas Selectos de Dirección de');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('025574','Temas Selectos de Dirección de');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024771','Funcionalidad auditiva para ha');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('024776','Dificultades lingüísticas y su');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027558','Psicología Positiva');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026925','Bioética');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027553','Bioética');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('025949','Bioética');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026926','Seminario de Proyecto II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027554','Seminario de Proyecto II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('025950','Seminario de Proyecto II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027555','Terapia Cognitivo - Conductual');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('025956','Psicología Laboral en Escenari');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027557','Psicopatología II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('025957','Capacitación y Desarrollo');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026930','Rehabilitación Neuropsicológic');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026928','Intervención Neuro. Infantil');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026927','Prácticas Profesionales II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('027556','Prácticas Profesionales II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('025951','Prácticas Profesionales II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('026929','Neurobiología II');
INSERT INTO Modulo (id_curso, nombre_modulo) VALUES ('025955','Administración del Personal');
