UPDATE Clase_programa SET num_alunos=5 where no_clase = '1401' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1402' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1403' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1404' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1405' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1406' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1407' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1408' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=18 where no_clase = '1409' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1410' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1411' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=6 where no_clase = '1413' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1416' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1417' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1419' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=6 where no_clase = '1420' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1424' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=10 where no_clase = '1425' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1426' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=25 where no_clase = '1428' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1429' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1430' and programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Clase_programa SET num_alunos=16 where no_clase = '1431' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1432' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1433' and programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1434' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1436' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=6 where no_clase = '1438' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1439' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1440' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1441' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1442' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=5 where no_clase = '1444' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1445' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1448' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1449' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=8 where no_clase = '1450' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1451' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1454' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=7 where no_clase = '1455' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1456' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1457' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1458' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=5 where no_clase = '1460' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1461' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=7 where no_clase = '1462' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1463' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1464' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=6 where no_clase = '1465' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1466' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=5 where no_clase = '1468' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1469' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=6 where no_clase = '1472' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=5 where no_clase = '1473' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1474' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1475' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1476' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1477' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1479' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=16 where no_clase = '1481' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1482' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1483' and programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Clase_programa SET num_alunos=6 where no_clase = '1484' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1485' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=33 where no_clase = '1486' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1488' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1489' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=26 where no_clase = '1490' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1491' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1492' and programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1493' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=10 where no_clase = '1494' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1495' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=10 where no_clase = '1496' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1497' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1498' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=6 where no_clase = '1500' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1501' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=17 where no_clase = '1502' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1503' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1506' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=6 where no_clase = '1508' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1509' and programa = 'Maestría en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1510' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1512' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1513' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1515' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1517' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1518' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=27 where no_clase = '1520' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1521' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=13 where no_clase = '1522' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1523' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1524' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1526' and programa = 'Maestría en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1528' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1530' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1531' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1532' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1533' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1536' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1537' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1538' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=11 where no_clase = '1539' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1540' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1541' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1542' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=26 where no_clase = '1543' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1544' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=10 where no_clase = '1545' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=9 where no_clase = '1548' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1550' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=35 where no_clase = '1551' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=25 where no_clase = '1553' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1554' and programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1555' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=13 where no_clase = '1556' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1558' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1559' and programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1560' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1561' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1564' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=5 where no_clase = '1565' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=23 where no_clase = '1566' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=11 where no_clase = '1568' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=11 where no_clase = '1569' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1570' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1571' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1572' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1587' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1588' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=10 where no_clase = '1589' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=15 where no_clase = '1590' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1592' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1593' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1594' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1596' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1597' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1599' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=22 where no_clase = '1600' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1601' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1602' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1603' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1604' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1605' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1606' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=5 where no_clase = '1607' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1608' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1610' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1612' and programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Clase_programa SET num_alunos=9 where no_clase = '1613' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1616' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1617' and programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1618' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1620' and programa = 'Maestría en Ingeniería y Gestión de la Cadena de Suministro';
UPDATE Clase_programa SET num_alunos=7 where no_clase = '1621' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1622' and programa = 'Maestría en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1623' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '1624' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=3 where no_clase = '1625' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=5 where no_clase = '1626' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '1627' and programa = 'Especialidad en Logística Internacional';
UPDATE Clase_programa SET num_alunos=2 where no_clase = '1628' and programa = 'Especialidad en Simuladores Gráficos';
UPDATE Clase_programa SET num_alunos=25 where no_clase = '1689' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=10 where no_clase = '1774' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=25 where no_clase = '1775' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1794' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=23 where no_clase = '1795' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=11 where no_clase = '1796' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=23 where no_clase = '1798' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=15 where no_clase = '1799' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1800' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1802' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=6 where no_clase = '9507' and programa = 'Especialidad en Ingeniería y Gestión Ambiental';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '9530' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '9531' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=5 where no_clase = '9532' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '9533' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '9535' and programa = 'Especialidad en Robótica y Manufactura';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '9536' and programa = 'Maestría en Ingeniería';
UPDATE Clase_programa SET num_alunos=21 where no_clase = '9539' and programa = 'Maestría en Ciencia de Datos';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '9899' and programa = 'Doctorado en Inteligencia Artificial';
UPDATE Clase_programa SET num_alunos=1 where no_clase = '9939' and programa = 'Especialidad en Dirección de Operaciones';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '9940' and programa = 'Especialidad en Ingeniería y Gestión de Proyectos';
UPDATE Clase_programa SET num_alunos=4 where no_clase = '10235' and programa = 'Especialidad en Simuladores Gráficos';
