UPDATE Clase_programa SET num_alunos=18.0 where no_clase = '10654' and programa = 'Maestría en Gobierno y Políticas Públicas';
UPDATE Clase_programa SET num_alunos=18.0 where no_clase = '10653' and programa = 'Maestría en Gobierno y Políticas Públicas';
UPDATE Clase_programa SET num_alunos=12.0 where no_clase = '11609' and programa = 'Maestría en Anticorrupción';
UPDATE Clase_programa SET num_alunos=0.0 where no_clase = '11599' and programa = 'Maestría en Anticorrupción';
UPDATE Clase_programa SET num_alunos=12.0 where no_clase = '11614' and programa = 'Maestría en Anticorrupción';
UPDATE Clase_programa SET num_alunos=12.0 where no_clase = '11608' and programa = 'Maestría en Anticorrupción';
UPDATE Clase_programa SET num_alunos=3.0 where no_clase = '1398' and programa = 'Maestría en Filosofía Antigua';
UPDATE Clase_programa SET num_alunos=5.0 where no_clase = '1396' and programa = 'Maestría en Filosofía Antigua';
UPDATE Clase_programa SET num_alunos=16.0 where no_clase = '1579' and programa = 'Maestría en Historia del Pensamiento';
UPDATE Clase_programa SET num_alunos=12.0 where no_clase = '1581' and programa = 'Maestría en Historia del Pensamiento';
UPDATE Clase_programa SET num_alunos=5.0 where no_clase = '1399' and programa = 'Maestría en Filosofía Antigua';
UPDATE Clase_programa SET num_alunos=4.0 where no_clase = '1400' and programa = 'Maestría en Filosofía Antigua';
UPDATE Clase_programa SET num_alunos=9.0 where no_clase = '1395' and programa = 'Maestría en Filosofía Antigua';
UPDATE Clase_programa SET num_alunos=12.0 where no_clase = '1584' and programa = 'Maestría en Historia del Pensamiento';
UPDATE Clase_programa SET num_alunos=12.0 where no_clase = '1580' and programa = 'Maestría en Historia del Pensamiento';
UPDATE Clase_programa SET num_alunos=16.0 where no_clase = '1577' and programa = 'Maestría en Historia del Pensamiento';
UPDATE Clase_programa SET num_alunos=9.0 where no_clase = '1397' and programa = 'Maestría en Filosofía Antigua';
UPDATE Clase_programa SET num_alunos=16.0 where no_clase = '1574' and programa = 'Maestría en Historia del Pensamiento';
UPDATE Clase_programa SET num_alunos=8.0 where no_clase = '1441' and programa = 'Especialidad en Desarrollo del Talento Humano';
UPDATE Clase_programa SET num_alunos=20.0 where no_clase = '1172' and programa = 'Maestría en Neuropsicología y Educación';
UPDATE Clase_programa SET num_alunos=20.0 where no_clase = '1192' and programa = 'Maestría en Neuropsicología y Educación';
UPDATE Clase_programa SET num_alunos=25.0 where no_clase = '1208' and programa = 'Maestría en Neuropsicología y Educación';
UPDATE Clase_programa SET num_alunos=25.0 where no_clase = '1194' and programa = 'Maestría en Neuropsicología y Educación';
UPDATE Clase_programa SET num_alunos=25.0 where no_clase = '1254' and programa = 'Maestría en Neuropsicología y Educación';
UPDATE Clase_programa SET num_alunos=20.0 where no_clase = '1193' and programa = 'Maestría en Neuropsicología y Educación';
UPDATE Clase_programa SET num_alunos=25.0 where no_clase = '1257' and programa = 'Maestría en Neuropsicología y Educación';
UPDATE Clase_programa SET num_alunos=20.0 where no_clase = '1174' and programa = 'Maestría en Neuropsicología y Educación';
UPDATE Clase_programa SET num_alunos=11.0 where no_clase = '1376' and programa = 'Maestría en Dirección del Capital Humano';
UPDATE Clase_programa SET num_alunos=12.0 where no_clase = '1377' and programa = 'Maestría en Dirección del Capital Humano';
UPDATE Clase_programa SET num_alunos=23.0 where no_clase = '1362' and programa = 'Maestría en Dirección del Capital Humano';
UPDATE Clase_programa SET num_alunos=16.0 where no_clase = '1387' and programa = 'Maestría en Dirección del Capital Humano';
UPDATE Clase_programa SET num_alunos=9.0 where no_clase = '1368' and programa = 'Maestría en Dirección del Capital Humano';
UPDATE Clase_programa SET num_alunos=9.0 where no_clase = '1369' and programa = 'Maestría en Dirección del Capital Humano';
UPDATE Clase_programa SET num_alunos=10.0 where no_clase = '1371' and programa = 'Maestría en Dirección del Capital Humano';
UPDATE Clase_programa SET num_alunos=9.0 where no_clase = '1375' and programa = 'Maestría en Dirección del Capital Humano';
UPDATE Clase_programa SET num_alunos=6.0 where no_clase = '1360' and programa = 'Maestría en Dirección del Capital Humano';
UPDATE Clase_programa SET num_alunos=12.0 where no_clase = '1361' and programa = 'Maestría en Dirección del Capital Humano';
UPDATE Clase_programa SET num_alunos=12.0 where no_clase = '1365' and programa = 'Maestría en Dirección del Capital Humano';
UPDATE Clase_programa SET num_alunos=8.0 where no_clase = '8784' and programa = 'Maestría en Dirección de Instituciones Educativas';
UPDATE Clase_programa SET num_alunos=4.0 where no_clase = '8785' and programa = 'Maestría en Dirección de Instituciones Educativas';
UPDATE Clase_programa SET num_alunos=8.0 where no_clase = '7245' and programa = 'Maestría en Dirección de Instituciones Educativas';
UPDATE Clase_programa SET num_alunos=7.0 where no_clase = '7248' and programa = 'Maestría en Dirección de Instituciones Educativas';
UPDATE Clase_programa SET num_alunos=8.0 where no_clase = '7247' and programa = 'Maestría en Dirección de Instituciones Educativas';
UPDATE Clase_programa SET num_alunos=8.0 where no_clase = '7246' and programa = 'Maestría en Dirección de Instituciones Educativas';
UPDATE Clase_programa SET num_alunos=8.0 where no_clase = '7249' and programa = 'Maestría en Dirección de Instituciones Educativas';
