UPDATE Clase_programa SET num_alunos=20 where no_clase = '1335' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1336' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1278' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1284' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1330' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1332' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1334' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1337' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1338' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1348' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1350' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1351' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1352' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1353' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1354' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1355' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1356' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1304' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1305' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1306' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1307' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1308' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1309' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1310' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1311' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1312' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1313' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1314' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1315' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1316' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1317' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1318' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1262' and programa = 'Maestría en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1266' and programa = 'Maestría en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1268' and programa = 'Maestría en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1271' and programa = 'Maestría en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1003' and programa = 'Maestría en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1274' and programa = 'Maestría en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=40 where no_clase = '1005' and programa = 'Maestría en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1196' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1197' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1198' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1207' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1199' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1200' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1201' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1202' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1203' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1204' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1205' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1206' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=14 where no_clase = '1207' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1080' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1079' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1078' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1077' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1076' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1075' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1074' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1073' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1072' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1071' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1070' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1069' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1068' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1067' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1066' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1065' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1064' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=12 where no_clase = '1063' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1243' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1242' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1241' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1240' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1239' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1237' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1236' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1238' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1244' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1245' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1246' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1247' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1248' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1249' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1250' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=32 where no_clase = '1251' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7399' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7402' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7406' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7407' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7408' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7409' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7410' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7411' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7412' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7413' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7414' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7415' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '7416' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1327' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1328' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1329' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1331' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1333' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1341' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1345' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1344' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1343' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1349' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1342' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=24 where no_clase = '1340' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1153' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1145' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1159' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1169' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1162' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1647' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1649' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1648' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1650' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos=19 where no_clase = '1651' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos=25 where no_clase = '1280' and programa = 'Maestría en Derecho Fiscal';
UPDATE Clase_programa SET num_alunos=25 where no_clase = '1281' and programa = 'Maestría en Derecho Fiscal';
UPDATE Clase_programa SET num_alunos=25 where no_clase = '1282' and programa = 'Maestría en Derecho Fiscal';
UPDATE Clase_programa SET num_alunos=25 where no_clase = '1283' and programa = 'Maestría en Derecho Fiscal';
UPDATE Clase_programa SET num_alunos=25 where no_clase = '1296' and programa = 'Maestría en Derecho Fiscal';
UPDATE Clase_programa SET num_alunos=25 where no_clase = '1298' and programa = 'Maestría en Derecho Fiscal';
UPDATE Clase_programa SET num_alunos=25 where no_clase = '2698' and programa = 'Maestría en Derecho Fiscal';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1325' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1323' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1322' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1324' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1573' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1576' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1575' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1578' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1643' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1644' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1645' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=20 where no_clase = '1646' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos=15 where no_clase = '1233' and programa = 'Doctorado en Derecho';
UPDATE Clase_programa SET num_alunos=15 where no_clase = '1234' and programa = 'Doctorado en Derecho';
UPDATE Clase_programa SET num_alunos=15 where no_clase = '1235' and programa = 'Doctorado en Derecho';
UPDATE Clase_programa SET num_alunos=15 where no_clase = '1547' and programa = 'Doctorado en Derecho';
UPDATE Clase_programa SET num_alunos=15 where no_clase = '1557' and programa = 'Doctorado en Derecho';
UPDATE Clase_programa SET num_alunos=15 where no_clase = '1562' and programa = 'Doctorado en Derecho';
