INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Gestión de las Artes y Políticas Culturales', 'Maestría', 'Profesionalizante', 'MGAP','Bellas Artes');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Neuropsicología', 'Especialidad', 'Profesionalizante', 'EN','Ciencias de la Salud');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Psicología Clínica y Salud', 'Especialidad', 'Profesionalizante', 'EPCS','Ciencias de la Salud');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Psicología Educativa', 'Especialidad', 'Profesionalizante', 'EPE','Ciencias de la Salud');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Psicología Organizacional', 'Especialidad', 'Profesionalizante', 'EPO','Ciencias de la Salud');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Terapia de Heridas, Estomas y Quemaduras', 'Especialidad', 'Profesionalizante', 'ETHEQ','Ciencias de la Salud');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Bioética', 'Maestría', 'Profesionalizante', 'MBIO','Ciencias de la Salud');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Terapia de Heridas, Estomas y Quemaduras', 'Maestría', 'Profesionalizante', 'MTHEQ','Ciencias de la Salud');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Doctorado en Bioética', 'Doctorado', 'Investigación', 'DBIO','Ciencias de la Salud');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Publicidad y Creación de Contenidos', 'Especialidad', 'Profesionalizante', 'EPCC','Comunicación');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Relaciones Públicas y Reputación de Marca', 'Especialidad', 'Profesionalizante', 'ERPRM','Comunicación');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Comunicación Institucional', 'Maestría', 'Profesionalizante', 'MCOMI','Comunicación');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Comunicación Política y Pública', 'Maestría', 'Profesionalizante', 'MCPP','Comunicación');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Comunicaciones de Marca', 'Maestría', 'Profesionalizante', 'MCM','Comunicación');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Narrativa y Producción Audiovisual', 'Maestría', 'Profesionalizante', 'MNPAU','Comunicación');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Derecho de Amparo', 'Especialidad', 'Profesionalizante', 'EDAMP','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Derecho de la Empresa', 'Especialidad', 'Profesionalizante', 'EDEMP','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Derecho Procesal Civil y Mercantil', 'Especialidad', 'Profesionalizante', 'EDPCM','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Ciencias Jurídicas', 'Maestría', 'Investigación', 'MCJUR','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Derecho Administrativo', 'Maestría', 'Profesionalizante', 'MDADM','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Derecho Constitucional y Derechos Humanos', 'Maestría', 'Profesionalizante', 'MDCDH','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Derecho de la Empresa', 'Maestría', 'Profesionalizante', 'MDEES','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Derecho Fiscal', 'Maestría', 'Profesionalizante', 'MDERF','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Derecho Laboral', 'Maestría', 'Profesionalizante', 'MDLA','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Derecho Procesal Constitucional', 'Maestría', 'Profesionalizante', 'MDEPC','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Instituciones de Derecho Financiero', 'Maestría', 'Profesionalizante', 'MIDFS','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Doctorado en Derecho', 'Doctorado', 'Investigación', 'DDER','Derecho');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Administración de Proyectos', 'Maestría', 'Profesionalizante', 'MAP','Empresariales');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Dirección del Capital Humano', 'Maestría', 'Profesionalizante', 'MDICH','Empresariales');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Finanzas', 'Maestría', 'Profesionalizante', 'MFIN','Empresariales');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Mercadotecnia Estratégica', 'Maestría', 'Profesionalizante', 'MME','Empresariales');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Negocios Internacionales', 'Maestría', 'Profesionalizante', 'MNI','Empresariales');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Impuestos', 'Maestría', 'Profesionalizante', 'MIMP','Empresariales');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría Internacional en Finanzas', 'Maestría', 'Directiva', 'MIF','Empresariales');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Doctorado en Ciencias Empresariales', 'Doctorado', 'Investigación', 'DCE','Empresariales');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', 'Especialidad', 'Profesionalizante', 'EENAR','ESDAI');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Gestión de Eventos', 'Especialidad', 'Profesionalizante', 'EGEVR','ESDAI');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Dirección de Instituciones de Salud', 'Maestría', 'Profesionalizante', 'MDISS','ESDAI');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Filosofía Antigua', 'Maestría', 'Investigación', 'MFIAT','Filosofía');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Historia del Pensamiento', 'Maestría', 'Investigación', 'MHPS','Filosofía');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Doctorado en Historia del Pensamiento', 'Doctorado', 'Investigación', 'DHISP','Filosofía');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Anticorrupción', 'Maestría', 'Profesionalizante', 'MACS','Gobierno y Economía');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Gobierno y Políticas Públicas', 'Maestría', 'Profesionalizante', 'MGPP','Gobierno y Economía');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Dirección de Operaciones', 'Especialidad', 'Profesionalizante', 'EDIOP ','Ingeniería');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', 'Especialidad', 'Profesionalizante', 'EIGA','Ingeniería');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', 'Especialidad', 'Profesionalizante', 'EIGEP','Ingeniería');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Logística Internacional', 'Especialidad', 'Profesionalizante', 'ELOIN ','Ingeniería');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Robótica y Manufactura', 'Especialidad', 'Profesionalizante', 'EROMA','Ingeniería');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Especialidad en Simuladores Gráficos', 'Especialidad', 'Profesionalizante', 'ESIMG ','Ingeniería');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Ciencia de Datos', 'Maestría', 'Profesionalizante', 'MCD','Ingeniería');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Dirección de Operaciones', 'Maestría', 'Profesionalizante', 'MDIOP','Ingeniería');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Ingeniería', 'Maestría', 'Profesionalizante', 'MING','Ingeniería');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministro', 'Maestría', 'Profesionalizante', 'MIGC','Ingeniería');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Doctorado en Inteligencia Artificial', 'Doctorado', 'Investigación', 'DIA','Ingeniería');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Dirección de Capital Humano', 'Maestría', 'Profesionalizante', 'MDICH','Pedagogía');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Dirección de Instituciones Educativas', 'Maestría', 'Profesionalizante', 'MDIES','Pedagogía');
INSERT INTO Programa (programa, grado, tipo,codigo,escuela) VALUES ('Maestría en Neuropsicología y Educación', 'Maestría', 'Profesionalizante', 'MNE','Pedagogía');
INSERT INTO Programa (programa, escuela) VALUES ('Esp. en Publicidad y Relaciones Públicas','Comunicación');
INSERT INTO Programa (programa, escuela) VALUES ('Especialidad en Antropología Filosófica','Humanidades');
INSERT INTO Programa (programa, escuela) VALUES ('Especialidad en Desarrollo del Talento Humano','Pedagogía');
INSERT INTO Programa (programa, escuela) VALUES ('Doctorado en Historia del pensamiento','Humanidades');
INSERT INTO Programa (programa, escuela) VALUES ('Doctorado en Historia del pensamiento','Humanidades');
