INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Gestión de las Artes y Políticas Culturales', 'gmoreno@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Gestión de las Artes y Políticas Culturales', 'gmoreno@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Gestión de las Artes y Políticas Culturales', 'gmoreno@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Terapia de Heridas, Estomas y Quemaduras', 'belopez@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Terapia de Heridas, Estomas y Quemaduras', 'belopez@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Neuropsicología', 'anherrera@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Neuropsicología', 'anherrera@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Psicología Clínica y Salud', 'anherrera@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Psicología Clínica y Salud', 'anherrera@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Psicología Educativa', 'anherrera@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Psicología Educativa', 'anherrera@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Psicología Organizacional', 'anherrera@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Psicología Organizacional', 'anherrera@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Bioética', 'cvillanuevas@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Bioética', 'cvillanuevas@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Terapia de Heridas, Estomas y Quemaduras', 'belopez@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Terapia de Heridas, Estomas y Quemaduras', 'belopez@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Bioética', 'gcantu@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Bioética', 'gcantu@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Publicidad y Creación de Contenidos', 'alopezm@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Publicidad y Creación de Contenidos', 'gsierrap@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Publicidad y Creación de Contenidos', 'sbarquet@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Relaciones Públicas y Reputación de Marca', 'alopezm@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Relaciones Públicas y Reputación de Marca', 'gsierrap@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Relaciones Públicas y Reputación de Marca', 'sbarquet@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Comunicación Institucional', 'alopezm@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Comunicación Institucional', 'gsierrap@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Comunicación Institucional', 'jrincon@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Comunicaciones de Marca', 'alopezm@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Comunicaciones de Marca', 'gsierrap@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Comunicación Política y Pública', 'alopezm@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Comunicación Política y Pública', 'gechevarria@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Narrativa y Producción Audiovisual', 'alopezm@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Narrativa y Producción Audiovisual', 'gsierrap@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Narrativa y Producción Audiovisual', 'sbarquet@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Derecho de Amparo', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Derecho de Amparo', 'omejia@up.edu.mx', 'Asistente');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Derecho de Amparo', 'mbartolini@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Derecho de la Empresa', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Derecho de la Empresa', 'mrs@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Derecho de la Empresa', 'mgarcia@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Derecho Procesal Civil y Mercantil', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Derecho Procesal Civil y Mercantil', 'omejia@up.edu.mx', 'Asistente');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Derecho Procesal Civil y Mercantil', 'idelrio@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ciencias Jurídicas', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ciencias Jurídicas', 'mrs@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ciencias Jurídicas', 'jfdiez@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Administrativo', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Administrativo', 'mrs@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Administrativo', 'gtejeda@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Constitucional y Derechos Humanos', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Constitucional y Derechos Humanos', 'bherjua@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Constitucional y Derechos Humanos', 'kfranck@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Fiscal', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Fiscal', 'bherjua@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Fiscal', 'gtejeda@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Instituciones de Derecho Financiero', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Instituciones de Derecho Financiero', 'irebollar@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Instituciones de Derecho Financiero', 'amarcial@up.edu.mx', 'Asistente');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Procesal Constitucional', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Procesal Constitucional', 'bherjua@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Procesal Constitucional', 'kfranck@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho de la Empresa', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho de la Empresa', 'irebollar@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho de la Empresa', 'amarcial@up.edu.mx', 'Asistente');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho de la Empresa', 'peruizba@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Laboral', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Laboral', 'mrs@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Derecho Laboral', 'mgarcia@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Derecho', 'agonzalezar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Derecho', 'aarceopa@up.edu.mx', 'Asistente');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Derecho', 'jcasanovas@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Derecho', 'hsramire@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Administración de Proyectos', 'bdupre@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Administración de Proyectos', 'ndiaz@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Administración de Proyectos', 'rguzman@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección del Capital Humano', 'bdupre@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección del Capital Humano', 'ndiaz@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección del Capital Humano', 'rguzman@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Finanzas', 'dscasillas@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Finanzas', 'emorales@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Finanzas', 'dortiz@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Mercadotecnia Estratégica', 'cdejesus@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Mercadotecnia Estratégica', 'emorales@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Mercadotecnia Estratégica', 'dlopezm@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Negocios Internacionales', 'cdejesus@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Negocios Internacionales', 'ndiaz@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Negocios Internacionales', 'rguzman@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Impuestos', 'dscasillas@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Impuestos', 'emorales@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Impuestos', 'dortiz@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría Internacional en Finanzas', 'cdejesus@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría Internacional en Finanzas', 'emorales@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría Internacional en Finanzas', 'dlopezm@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Ciencias Empresariales', 'cdejesus@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', 'lpfernandez@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', 'jtronp@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Emprendedores de Negocios de Alimentos y Bebidas', 'mbasurto@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Gestión de Eventos', 'lpfernandez@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Gestión de Eventos', 'jtronp@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Gestión de Eventos', 'mbasurto@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección de Instituciones de Salud', 'lpfernandez@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección de Instituciones de Salud', 'jtronp@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección de Instituciones de Salud', 'mbasurto@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Filosofía Antigua', 'jgarciac@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Filosofía Antigua', 'mlecon@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Filosofía Antigua', 'mlecon@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Historia del Pensamiento', 'jgarciac@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Historia del Pensamiento', 'jgarciac@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Historia del Pensamiento', 'mlecon@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Historia del Pensamiento', 'jgarciac@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Historia del Pensamiento', 'jgarciac@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Historia del Pensamiento', 'mlecon@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Anticorrupción', 'cgherrera@up.edu.mx ', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Anticorrupción', 'cgherrera@up.edu.mx ', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Anticorrupción', 'hcasillas@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Gobierno y Políticas Públicas', 'rmartinezm@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Gobierno y Políticas Públicas', 'rmartinezm@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Gobierno y Políticas Públicas', 'hcasillas@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Dirección de Operaciones', 'caperez@up.edu.mx ', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Dirección de Operaciones', 'laberumen@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Dirección de Operaciones', 'laberumen@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', 'ssanchez@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', 'cwelsh@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Ingeniería y Gestión Ambiental', 'olozada@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', 'caperez@up.edu.mx ', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', 'laberumen@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Ingeniería y Gestión de Proyectos', 'cwelsh@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Logística Internacional', 'caperez@up.edu.mx ', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Logística Internacional', 'laberumen@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Logística Internacional', 'laberumen@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Robótica y Manufactura', 'ssanchez@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Robótica y Manufactura', 'cwelsh@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Robótica y Manufactura', 'olozada@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Simuladores Gráficos', 'ssanchez@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Simuladores Gráficos', 'cwelsh@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Especialidad en Simuladores Gráficos', 'olozada@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección de Operaciones', 'caperez@up.edu.mx ', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección de Operaciones', 'laberumen@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección de Operaciones', 'laberumen@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ingeniería', 'caperez@up.edu.mx ', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ingeniería', 'cwelsh@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ingeniería', 'cwelsh@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ciencia de Datos', 'ssanchez@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ciencia de Datos', 'mhurtado@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ciencia de Datos', 'mhurtado@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministro', 'caperez@up.edu.mx ', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministro', 'laberumen@up.edu.mx', 'Coordinador Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Ingeniería y Gestión de la Cadena de Suministro', 'laberumen@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Inteligencia Artificial', 'ssanchez@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Doctorado en Inteligencia Artificial', 'hponce@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección de Capital Humano', 'ltovar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección de Capital Humano', 'imoya@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección de Instituciones Educativas', 'ltovar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Dirección de Instituciones Educativas', 'imoya@up.edu.mx', 'Jefe Académico');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Neuropsicología y Educación', 'ltovar@up.edu.mx', 'Coordinador de Promoción y Admisiones');
INSERT INTO Puesto_programa (programa, email_persona, puesto) VALUES ('Maestría en Neuropsicología y Educación', 'mejimene@up.edu.mx', 'Jefe Académico');
