INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Bellas Artes', 'gpliego@up.edu.mx', 'Director E/F');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Bellas Artes', 'gmoreno@up.edu.mx', 'Director Posgrado');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Bellas Artes', 'dduarte@up.edu.mx', 'Secretario Administrativo');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Ciencias de la Salud', 'gobrador@up.edu.mx', 'Director E/F');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Ciencias de la Salud', 'ijuarez@up.edu.mx', 'Subdirector Posgrado');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Ciencias de la Salud', 'tsepulve@up.edu.mx', 'Secretario Administrativo');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Comunicación', 'mnavarroa@up.edu.mx', 'Director E/F');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Comunicación', 'lgarduno@up.edu.mx', 'Director Posgrado');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Comunicación', 'jjvargas@up.edu.mx', 'Secretario Administrativo');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Derecho', 'fbatista@up.edu.mx', 'Director E/F');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Derecho', 'cpreciado@up.edu.mx', 'Director Posgrado');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Derecho', 'mjimenez@up.edu.mx', 'Secretario Administrativo');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Empresariales', 'eugonzal@up.edu.mx', 'Director E/F');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Empresariales', 'mpaniagu@up.edu.mx', 'Director Posgrado');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Empresariales', 'arlimas@up.edu.mx', 'Secretario Administrativo');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Empresariales', 'cdejesus@up.edu.mx', 'Jefe Promoción y Admisiones');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('ESDAI', 'amgarciac@up.edu.mx', 'Director E/F');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('ESDAI', 'vroarof@up.edu.mx', 'Director Posgrado');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('ESDAI', 'gtorresm@up.edu.mx', 'Secretario Administrativo');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('ESDAI', 'farteagar@up.edu.mx', 'Jefe Promoción y Admisiones');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Filosofía', 'mepelaez@up.edu.mx', 'Director E/F');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Filosofía', 'mlecon@up.edu.mx', 'Director Posgrado');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Filosofía', 'ggalvan@up.edu.mx', 'Secretario Administrativo');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Gobierno y Economía', 'gtenorio@up.edu.mx', 'Director E/F');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Gobierno y Economía', 'fgamboa@up.edu.mx', 'Director Posgrado');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Gobierno y Economía', 'ejimeneza@up.edu.mx', 'Secretario Administrativo');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Ingeniería', 'aordonet@up.edu.mx', 'Director E/F');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Ingeniería', 'jpardo@up.edu.mx', 'Director Posgrado');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Ingeniería', 'crohde@up.edu.mx', 'Secretario Administrativo');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Ingeniería', 'fcal@up.edu.mx', 'Coordinador de Asuntos Estudiantiles');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Pedagogía', 'mvillarreal@up.edu.mx', 'Director E/F');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Pedagogía', 'jcobela@up.edu.mx', 'Director Posgrado');
INSERT INTO Puesto_escuela (escuela, email_persona, puesto) VALUES ('Pedagogía', 'ggalvan@up.edu.mx', 'Secretario Administrativo');
