INSERT INTO Salon (salon, isla, sede) VALUES ('A 02', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('AULA MAGNA', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('BUSNS_LAB', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('C 04', 'Campana', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('C 05', 'Campana', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('C 07', 'Campana', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('C 01', 'Campana', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('C 02', 'Campana', 'Mixcoac');

INSERT INTO Salon (salon, isla, sede) VALUES ('CDC_A', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('CDC_B', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('CDC_C', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('CDC_E', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('D 05', 'Donatello', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('D 06', 'Donatello', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('D 02', 'Donatello', 'Mixcoac');


INSERT INTO Salon (salon, isla, sede) VALUES ('D 09', 'Donatello', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('D 10', 'Donatello', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('D 11', 'Donatello', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('JEREZ 01', 'Jerez / Zona Cielito', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('JEREZ 02', 'Jerez / Zona Cielito', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('JEREZ 03', 'Jerez / Zona Cielito', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('JEREZ 04', 'Jerez / Zona Cielito', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('JEREZ 05', 'Jerez / Zona Cielito', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('NR 01', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('NR 02', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('NR 03', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('NR 04', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('NR 05', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('NR 06', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('NR 07', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('NR 08', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('NR 09', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('P 03', 'Periquillo', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 01', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 02', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 03', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 04', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 05', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 06', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 07', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 08', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 09', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 10', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 11', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 12', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 13', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 14', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 15', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 16', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 17', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 18', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 19', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 20', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 21', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 24', 'Aula Magna / Comedor Invitados', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 25', 'Aula Magna / Comedor Invitados', 'Mixcoac');

INSERT INTO Salon (salon, isla, sede) VALUES ('R 27', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 28', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 29', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 30', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 31', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 32', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 33', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 34', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 35', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 36', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 37', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 38', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 39', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 40', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 41', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 42', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 43', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 44', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 45', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 46', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('R 47', 'Explanada de Biblioteca', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('V_LAB_ADIG', 'Jerez / Zona Cielito', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('V_LAB_COM1', 'Jerez / Zona Cielito', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('V_LAB_COM2', 'Jerez / Zona Cielito', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('SF_6-1', 'Santa Fe', 'Santa Fe');
INSERT INTO Salon (salon, isla, sede) VALUES ('SF_6-2', 'Santa Fe', 'Santa Fe');
INSERT INTO Salon (salon, isla, sede) VALUES ('SF_6-3', 'Santa Fe', 'Santa Fe');
INSERT INTO Salon (salon, isla, sede) VALUES ('SF_6-4', 'Santa Fe', 'Santa Fe');
INSERT INTO Salon (salon, isla, sede) VALUES ('SF_6-5', 'Santa Fe', 'Santa Fe');
INSERT INTO Salon (salon, isla, sede) VALUES ('SF_6-6', 'Santa Fe', 'Santa Fe');
INSERT INTO Salon (salon, isla, sede) VALUES ('SALA_JUNT_ING', 'Jerez / Zona Cielito', 'Mixcoac');
INSERT INTO Salon (salon, isla, sede) VALUES ('JUICIORAL', 'Jerez / Zona Cielito', 'Mixcoac');

