UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1350' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1351' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1352' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1353' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1354' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1355' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1356' and programa = 'Maestría en Derecho Laboral';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1308' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1309' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1310' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1311' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1312' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1313' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1314' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1315' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1316' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1317' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1318' and programa = 'Maestría en Instituciones de Derecho Financiero';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1268' and programa = 'Maestría en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 40 where no_clase = '1271' and programa = 'Maestría en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 14 where no_clase = '1199' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos= 14 where no_clase = '1201' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos= 14 where no_clase = '1202' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos= 14 where no_clase = '1203' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos= 14 where no_clase = '1204' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos= 14 where no_clase = '1205' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos= 14 where no_clase = '1206' and programa = 'Maestría en Ciencias Jurídicas';
UPDATE Clase_programa SET num_alunos= 12 where no_clase = '1079' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos= 12 where no_clase = '1078' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos= 12 where no_clase = '1077' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos= 12 where no_clase = '1076' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos= 12 where no_clase = '1075' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos= 12 where no_clase = '1074' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos= 12 where no_clase = '1073' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos= 12 where no_clase = '1072' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos= 12 where no_clase = '1071' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos= 12 where no_clase = '1070' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos= 12 where no_clase = '1069' and programa = 'Especialidad en Derecho Procesal Civil y Mercantil';
UPDATE Clase_programa SET num_alunos= 32 where no_clase = '1238' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos= 32 where no_clase = '1244' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos= 32 where no_clase = '1245' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos= 32 where no_clase = '1246' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos= 32 where no_clase = '1247' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos= 32 where no_clase = '1248' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos= 32 where no_clase = '1249' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos= 32 where no_clase = '1250' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos= 32 where no_clase = '1251' and programa = 'Especialidad en Derecho de Amparo';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7399' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7402' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7406' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7407' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7408' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7409' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7410' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7411' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7412' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7413' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7414' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7415' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '7416' and programa = 'Especialidad en Derecho de la Empresa';
UPDATE Clase_programa SET num_alunos= 24 where no_clase = '1329' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos= 24 where no_clase = '1331' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos= 24 where no_clase = '1333' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos= 24 where no_clase = '1345' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos= 24 where no_clase = '1344' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos= 24 where no_clase = '1349' and programa = 'Maestría en Derecho Administrativo';
UPDATE Clase_programa SET num_alunos= 19 where no_clase = '1169' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos= 19 where no_clase = '1650' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos= 19 where no_clase = '1651' and programa = 'Maestría en Derecho Constitucional y Derechos Humanos';
UPDATE Clase_programa SET num_alunos= 25 where no_clase = '1282' and programa = 'Maestría en Derecho Fiscal';
UPDATE Clase_programa SET num_alunos= 25 where no_clase = '1283' and programa = 'Maestría en Derecho Fiscal';
UPDATE Clase_programa SET num_alunos= 25 where no_clase = '2698' and programa = 'Maestría en Derecho Fiscal';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1573' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1576' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1575' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1643' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1644' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1645' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos= 20 where no_clase = '1646' and programa = 'Maestría en Derecho Procesal Constitucional';
UPDATE Clase_programa SET num_alunos= 15 where no_clase = '1234' and programa = 'Doctorado en Derecho';
UPDATE Clase_programa SET num_alunos= 15 where no_clase = '1562' and programa = 'Doctorado en Derecho';
